### ISSUE TITLE
Installation instruction needed

### ISSUE THREAD

**Issue by Gajusbonus** [inspired-futures/ipade#5]
Good work! 

I copied all you file to a webserver with a FQDN and it works out of the box.
So now it is setup to connect to  "meet.jit.si" server.

How can I make this work with my own server?
I have jitsi meet installed and working with my own urls, but I want to use breakoutroom, so I need the ipade front-end.
How can I edit your config.js in order to make it work with my own server?
In the file config.js there are nine references to  "meet.jit.si"
Can we replace with  "meet.jit.si" with "my.own.server.org"  ? Which lines need to point to this server?

**Comment by deleolajide** [comment]
see https://github.com/inspired-futures/ipade/blob/master/README.md
