### ISSUE TITLE
404 error in breakout room

### ISSUE THREAD

**Issue by pratik9722** [inspired-futures/ipade#9]
Just want to make you aware so that you can make improvements, your new breakout room gives 404 errors to the participants, while last year's breakout room was awesome. it was working without any problem.

**Comment by deleolajide** [comment]
Thanks for the feedback. 

Last year's version was using meet.jit.si. The current version is using pade.chat (my dev server) which is not reliable. You should clone the project and use your own reliable server

**Comment by candideu** [comment]
> 
> 
> Thanks for the feedback.
> 
> Last year's version was using meet.jit.si. The current version is using pade.chat (my dev server) which is not reliable. You should clone the project and use your own reliable server or use the Pade plugin for Openfire which is maintained. I am not supporting this code. It is just a demo and I am thinking of removing it as I can't maintain 2 versions of the same code.

How can we set it up with the meet.jit.si?
